apiVersion: apps/v1
kind: Deployment
metadata:
  name: go_echo
  labels:
    app: go_echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go_echo
  template:
    metadata:
      labels:
        app: go_echo
    spec:
      containers:
        - name: go_echo
          image: acrworkflow1709443935437.azurecr.io/image-workflow-1710623247432:latest
          ports:
            - containerPort: 80